name: Hello world workflow

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - #uses: actions/checkout@v3  : AI sætter ind pr. default
      - name: Run hello world
        run: echo "Hello world"
        shell: bash